<?php
echo '<!DOCTYPE html>';
echo '<html lang="cs">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" type="text/css" href="css/main.css">';
echo '<link rel="stylesheet" type="text/css" href="css/styleHeader.css">';
echo '<link rel="stylesheet" type="text/css" href="css/style.css">';
echo '<link rel="stylesheet" type="text/css" href="css/styleBar.css">';
echo '<link rel="stylesheet" type="text/css" href="css/top.css">';
echo '<link rel="stylesheet" type="text/css" href="css/bottomPart.css">';
echo '<link rel="stylesheet" type="text/css" href="css/OnLoadStyle.css">';
echo '';
echo '<script src="https://code.jquery.com/jquery-1.10.2.js"></script>';
echo '<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>';
echo '';
echo '<script src="js/visibility.js"></script>';
echo '';
echo '<title>Document</title>';
echo '';
echo '<style>';
echo 'body {';
echo 'text-align: justify;';
echo '}';
echo '';
echo '</style>';
echo '';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="mainContainer">';
echo '<section>';
echo '<header class="header" id="top">';
echo '<div class="headerFreeSpace"></div>';
echo '<div class="menu">';
echo '<ul class="obsahMenu">';
echo '<li><a class="active" href="index.php">HOME</a></li>';
echo '<li onmouseout="closeMenu()" onmouseover="openMenu()"><a class="mrTS" href="#home">O UNREAL';
echo 'ENGINE</a></li>';
echo '<li><a href="#home">DOKUMENTACE</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="dropdownContainerWrapper" id="dropdownContainerWrapper" onmouseout="closeMenu()"';
echo 'onmouseover="openMenu()">';
echo '<div class="dropdown">';
echo '<div class="dropdownMenuContainer h_fit">';
echo '<div class="dropdownText_L h_fit pc_drp_dwn">';
echo '<div>';
echo '<div class="headerUnrealEngineDropdownMenu">';
echo '<h1>Více infa</h1>';
echo '</div>';
echo '';
echo '<div class="paragraphUnrealEngineDropdownMenu">';
echo '<p>';
echo 'Lorem Ipsum has been the industrys standard dummy text ever since the Lorem';
echo 'Ipsum';
echo 'has been the industrys standard dummy text ever since the';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="h_fit pc_drp_dwn">';
echo '<ul class="dropdownMenu">';
echo '<li><a href="history.html">HISTORIE</a></li>';
echo '<li><a href="#home">VERZE</a></li>';
echo '<li><a href="Mapy.html">3D RENDERY</a></li>';
echo '<li><a href="hwreq.html">HW POŽADAVKY</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</header>';
echo '</section>';
echo '';
echo '<section>';
echo '<div class="topHeader">';
echo '<div class="headerUnrealEngine" style="margin: 0 1rem;">';
echo '<div class="h1UE">';
echo '<h1>Unreal Engine</h1>';
echo '</div>';
echo '<div class="noteUE">';
echo '<p>This engine is...</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section>';
echo '<div class="Container" style="margin-top: 10px;">';
echo '<div class="ContainerBack">';
echo '<main class="mainContentCointeiner">';
echo '<div class="content">';
echo '<div class="mainContentCointeiner" id="main">';
echo '<h6 id="accessibility-content" class="e_V e_S">Hlavní obsah</h6>';
echo '<div class="content">';
echo '<div class="Container" style="margin: 0 1rem;">';
echo '<div class="lomTitleDiv">';
echo '<h1 class="lomTitle">Úvod</h1>';
echo '</div>';
echo '<div class="lomOdstavec">';
echo '<p>';
echo '<span>';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo '</span>';
echo '</p>';
echo '</div>';
echo '';
echo '<div class="lomOdstavec">';
echo '<p>';
echo '<span>';
echo 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloribus aperiam ullam error';
echo 'nostrum hic illum saepe animi iusto perferendis. Possimus dolor veniam earum distinctio,';
echo 'quas voluptatum quisquam odit omnis delectus!';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rem optio atque, quam';
echo 'autem perspiciatis culpa quae amet laudantium. Pariatur dolorem officia voluptates,';
echo 'saepe ut assumenda quod accusamus. Ullam, impedit.';
echo 'Ut animi facere dicta doloribus autem culpa recusandae molestias amet impedit dolores';
echo 'sapiente, facilis quaerat fugiat tempore error possimus. Libero necessitatibus vero';
echo 'nostrum voluptatem aspernatur officiis commodi neque optio debitis.';
echo '</span>';
echo '</p>';
echo '';
echo '<div class="imgContainer">';
echo '<div>';
echo '<div>';
echo '<img src="https://cdn2.unrealengine.com/Unreal+Engine%2Fblog%2Fa-first-look-at-unreal-engine-5%2FUnreal_Engine_5_Nanite-2491x1401-110edc43c67b7d81be869bf703cb40a72e557c96.jpg?resize=1&w=1920"';
echo 'alt="CSKO" title="Obrázek" draggable="false">';
echo '</div>';
echo '<div class="imgComment">';
echo '<p style="display: flex;flex-direction: column;">';
echo '<span>';
echo 'Real time render v Unreal Engine 5 (Zdroj Epic Games)';
echo '</span>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="lomOdstavec">';
echo '<p>';
echo '<span>';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo '</span>';
echo '</p>';
echo '</div>';
echo '<div class="lomOdstavec">';
echo '<p>';
echo '<span>';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo '</span>';
echo '</p>';
echo '</div>';
echo '<div class="lomOdstavec">';
echo '<p>';
echo '<span>';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores! Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?';
echo '</span>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</main>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section aria-label="Dolní část">';
echo '<div class="bottomPart">';
echo '<div class="mainContentCointeiner" id="bottom">';
echo '<div class="bottomPartContent">';
echo '<div class="bottomPartContainerText">';
echo '<h2>Informace</h2>';
echo '<div class="bottomPartContainerTextWrapper">';
echo '<div class="bottomPartContainerLinks">';
echo '<div class="bottomPartContainerLinksCon">';
echo '<a href="https://facebook.com">';
echo '<div>';
echo '<svg';
echo 'width="16"';
echo 'height="16"';
echo 'viewBox="0 0 24 24"';
echo 'fill="none"';
echo 'xmlns="http://www.w3.org/2000/svg"';
echo '>';
echo '<path';
echo 'd="M9.19795 21.5H13.198V13.4901H16.8021L17.198 9.50977H13.198V7.5C13.198 6.94772 13.6457 6.5 14.198 6.5H17.198V2.5H14.198C11.4365 2.5 9.19795 4.73858 9.19795 7.5V9.50977H7.19795L6.80206 13.4901H9.19795V21.5Z"';
echo 'fill="currentColor"';
echo '/>';
echo '</svg>';
echo '<p>Facebook</p>';
echo '</div>';
echo '</a>';
echo '';
echo '<a href="https://instagram.com">';
echo '<div>';
echo '<svg';
echo 'width="16"';
echo 'height="16"';
echo 'viewBox="0 0 24 24"';
echo 'fill="none"';
echo 'xmlns="http://www.w3.org/2000/svg"';
echo '>';
echo '<path';
echo 'fill-rule="evenodd"';
echo 'clip-rule="evenodd"';
echo 'd="M12 7C9.23858 7 7 9.23858 7 12C7 14.7614 9.23858 17 12 17C14.7614 17 17 14.7614 17 12C17 9.23858 14.7614 7 12 7ZM9 12C9 13.6569 10.3431 15 12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12Z"';
echo 'fill="currentColor"';
echo '/>';
echo '<path';
echo 'd="M18 5C17.4477 5 17 5.44772 17 6C17 6.55228 17.4477 7 18 7C18.5523 7 19 6.55228 19 6C19 5.44772 18.5523 5 18 5Z"';
echo 'fill="currentColor"';
echo '/>';
echo '<path';
echo 'fill-rule="evenodd"';
echo 'clip-rule="evenodd"';
echo 'd="M5 1C2.79086 1 1 2.79086 1 5V19C1 21.2091 2.79086 23 5 23H19C21.2091 23 23 21.2091 23 19V5C23 2.79086 21.2091 1 19 1H5ZM19 3H5C3.89543 3 3 3.89543 3 5V19C3 20.1046 3.89543 21 5 21H19C20.1046 21 21 20.1046 21 19V5C21 3.89543 20.1046 3 19 3Z"';
echo 'fill="currentColor"';
echo '/>';
echo '</svg>';
echo '<p>Instagram</p>';
echo '</div>';
echo '</a>';
echo '';
echo '<a href="https://twitter.com">';
echo '<div>';
echo '<svg';
echo 'width="16"';
echo 'height="16"';
echo 'viewBox="0 0 24 24"';
echo 'fill="none"';
echo 'xmlns="http://www.w3.org/2000/svg"';
echo '>';
echo '<path';
echo 'fill-rule="evenodd"';
echo 'clip-rule="evenodd"';
echo 'd="M8 3C9.10457 3 10 3.89543 10 5V8H16C17.1046 8 18 8.89543 18 10C18 11.1046 17.1046 12 16 12H10V14C10 15.6569 11.3431 17 13 17H16C17.1046 17 18 17.8954 18 19C18 20.1046 17.1046 21 16 21H13C9.13401 21 6 17.866 6 14V5C6 3.89543 6.89543 3 8 3Z"';
echo 'fill="currentColor"';
echo '/>';
echo '</svg>';
echo '<p>Twitter</p>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="bottomPartNextToLinkstext">';
echo '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus modi voluptas';
echo 'necessitatibus sed consectetur, nostrum aut at sit nulla, repellat dolores!';
echo 'Repudiandae';
echo 'doloremque blanditiis ullam odit earum possimus, laborum numquam?</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<div style="display: block; text-align: center; color: rgba(255, 255, 255, 0.05); background: #0d1015; padding: 10px 0">';
echo '<p>(c) Tmej Vojtěch 14.10. 2022</p></div>';
echo '</div>';
echo '';
echo '</body>';
echo '';
echo '</html>';
?>